# Generated by Django 5.2 on 2025-04-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flux_model',
            field=models.CharField(default='black-forest-labs/flux-schnell', max_length=255),
        ),
    ]
