version: '3.9'

services:
  web:
    build: .
    command: gunicorn adnari.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./staticfiles:/app/staticfiles

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: automato
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
volumes:
  postgres_data: