version: '3.9'

services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./shorts:/app/shorts
      - ./temp_uploads:/app/temp_uploads
      - ./uploads:/app/uploads
      - ./staticfiles:/app/staticfiles
    ports:
      - "6182:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis
      - qdrant
      - db
    restart: always

  celery:
    build: .
    command: celery -A app worker --loglevel=info
    volumes:
      - ./shorts:/app/shorts
      - ./temp_uploads:/app/temp_uploads
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app  
    depends_on:
      - redis
      - db
    restart: always

  beat:
    build: .
    command: celery -A app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis
      - db
    restart: always

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    restart: always

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  qdrant_storage:
