name: Run notebooks

on: [ workflow_dispatch ]

jobs:
  run-notebooks:
    name: Run notebooks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - run: poetry install --with dev
